/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { forwardRef } from 'react';
import { useGLTF } from '@react-three/drei';

const Crossbow = forwardRef((props, ref) => {
	const { nodes, materials } = useGLTF(
		'https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/crossbow/model.gltf'
	);
	return (
		<group ref={ref} {...props} dispose={null}>
			<group rotation={[Math.PI * 1.55, Math.PI * 1, 0]} position={[-0.1,0,0.9]}>
				<mesh geometry={nodes.Cube065.geometry} material={materials['Metal.090']} />
				<mesh geometry={nodes.Cube065_1.geometry} material={materials['BrownDark.058']} />
			</group>
		</group>
	);
});

export default Crossbow;

useGLTF.preload(
	'https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/crossbow/model.gltf'
);
